source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '2.7.3'

gem 'cocoapods', '~> 1.12.1'
gem 'fastlane', '~> 2.212.2'
gem 'dotenv', '~> 2.8.1'
gem 'xcode-install', "~> 2.8.1"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)